/**
	Generated by sails-inverse-model
	Date:Fri Mar 23 2018 16:31:17 GMT+0530 (India Standard Time)
*/

module.exports = {
    attributes: {
        userid: {
            type: "integer"
        },
        name: {
            type: "string"
        },
        roll_number: {
            type: "string"
        },
        registration_number: {
            type: "string"
        },
        current_section: {
            type: "string"
        },
        current_year: {
            type: "string"
        },
        joining_year: {
            type: "string"
        },
        course: {
            type: "string"
        },
        branch: {
            type: "string"
        },
        gender: {},
        birthday: {
            type: "date"
        },
        country: {
            type: "string"
        },
        mobile: {
            type: "string"
        },
        emergency_contact: {
            type: "string"
        },
        sbh_account: {
            type: "string"
        },
        passport: {
            type: "string"
        },
        hostel_room: {
            type: "string"
        },
        hostel: {
            type: "string"
        },
        mess: {
            type: "string"
        },
        created_location: {
            type: "string"
        },
        created_time: {
            type: "string"
        },
        guardian1: {
            type: "string"
        },
        relationship1: {
            type: "string"
        },
        email1: {
            type: "string"
        },
        mobile1: {
            type: "string"
        },
        guardian2: {
            type: "string"
        },
        relationship2: {
            type: "string"
        },
        email2: {
            type: "string"
        },
        mobile2: {
            type: "string"
        },
        homenumber: {
            type: "string"
        },
        address: {
            type: "string"
        },
        bloodgroup: {
            type: "string"
        },
        adhaar: {
            type: "string"
        },
        linkedin: {
            type: "string"
        },
        mac: {
            type: "string"
        }
    }
};